var quotes = new Array(
"\"If the first grape you eat is bitter then you will not bother eating grapes again. If the first grape you eat is a sweet one then you will be willing to eat a lot of bitter grapes in search of another sweet one.\"",
"\"I swear to officer I'm not drinking God.\" - Ryan Kochie", 
"\"Do what's right. Do it right. Do it right now.\" - Malcolm Stevenson Forbes",
"\"May the road rise to meet you. May the wind always be at your back. May the sunshine warm upon your face, the rains fall soft upon your fields and, until we meet again, may God hold you in the palm of his hand.\" - Traditional Gaelic Blessing",
"\"Don't Piss Backwards\" - AJ Schultz ",
"\"Bah Weep Granah Weep Ninni Bong.\" - Universal Greeting (Transformers)",
"\"The rules have changed. True power is held by the person who possesses the largest bookshelf, not gun cabinet or wallet.\" - Anthony J. D'Angelo",
"\"You can fool some people sometimes, but you can't fool all the people all the time.\" - Bob Marley",
"\"Reality doesn't bite, rather our perception of reality bites.\" - Anthony J. D'Angelo",
"\"Open your eyes and your mind just might follow.\"",
"\"Never cut what you can untie.\" - Joseph Joubert",
"\"It usually takes a long time to find a shorter way.\"",
"\"Question authority. All authority, always.\" - Ryan Kochie",
"\"Beauty is lost on the unimaginative.\" - Ryan Kochie",
"\"The man who makes no mistakes does not make anything.\" - Edward John Phelps",
"\"The cake is a lie.\" - Portal (Video Game)",
"\"Love looks through a telescope; envy, through a microscope.\" - Josh Billings",
"\"A condom is the glass slipper for our generation. You slip one on when you meet a stranger. You dance all night, and then you throw it away.\" - Marla Singer (Fight Club)",
"\"Courage is not the absence of fear, but rather the judgment that something else is more important than fear.\" - Ambrose Redmoon",
"\"The heart is wiser than the intellect.\" - Josiah Gilbert Holland",
"\"One who walks in another's tracks leaves no footprints.\"",
"\"The road to a friend's house is never long.\"",
"\"There are 10 kinds of people in the world, those who know binary and those that don't.\"",
"\"If one does not understand a person, one tends to regard him as a fool.\" - Carl Gustav Jung",
"\"If the human mind was simple enough to understand, we'd be too simple to understand it.\" - Emerson Pugh",
"\"Procrastination is the art of keeping up with yesterday.\" - Don Marquis",
"\"The tragedy of life is not that it ends so soon, but that we wait so long to begin it.\" - W. M. Lewis",
"\"I am prepared to meet anyone, but whether anyone is prepared for the great ordeal of meeting me is another matter.\" - Mark Twain",
"\"They say a person needs just three things to be truly happy in this world: someone to love, something to do, and something to hope for.\" - Thomas Edward Bodett",
"\"War does not determine who is right, war determines who is left.\" - Bertrand Russell",
"\"Take chances, make mistakes, and get messy!\" - Miss Frizz",
"\"It takes both sunshine and rain to make a rainbow.\"",
"\"When we are with friends or family we are hindered by the past. When we are by ourselves we are hindered by the future. It is only in the company of strangers that we can be free and in the present moment. \" - Ryan Kochie",
"Opa!",
"\"I would if I could but I can't so I won't.\"",
"\"You must be the change you want to see in the world.\" - Mahatma Gandhi",
"\"Those who sling mud tend to lose ground.\"",
"\"It puts the lotion on its skin or else it gets the hose again.\" - Buffalo Bill (Silence Of The Lambs)",
"\"It's only after we've lost everything that were free to do anything.\" - Tyler Durden (Fight Club)",
"\"Like a rainbow, a rainbow in the dark.\" - Ronnie James Dio",
"\"Love starts with a hug, grows with a kiss, and ends with a tear.\"",
"\"If firefighters fight fire and crime fighters fight crime, what do freedom fighters fight?\" - George Carlin",
"\"Friends are Gods way of apologizing for our families.\"",
"\"By three methods we may learn from wisdom: first, by reflection, which is noblest; second, by imitation, which is easiest; and third by experience, which is the bitterest.\" - Confucius",
"\"I can resist anything but temptation.\" - Oscar Wilde",
"\"All who wander are not lost.\" - J.R.R. Tolkien",
"\"87% of life's problems can be solved with a little WD-40, a hammer and lots of duct tape.\" -Ryan Kochie",
"\"A free society is one where it is safe to be unpopular.\"",
"\"Whoever loves, let him flourish. Let him perish who knows not love. Let him perish twice over whoever forbids love.\" - Grafiti At Pompeii",
"\"You may only be one person to the world, but you may also be the world to one person.\"",
"\"Love is like war, easy to begin, hard to end.\" - H.L. Mencken",
"\"May today be better than yesterday, but, not as good as tomorrow.\"",
"\"Quitters never win, and winners never quit, but those who never quit AND never win are idiots.\"",
"\"Life is merely the temporary state of existence between non-death and death.\" - Ryan Kochie",
"\"Proofread carefully to see if you any words out.\"",
"\"The real measure of your wealth is how much you'd be worth if you lost all your money.\" - Bernard Meltzer",
"\"Life is a class for the soul.\"",
"\"Very specifically, I know nothing about everything.\" - Ryan Kochie",
"\"Hakuna Matata.\" - Timon And Pumba",
"\"If you could be either God's worst enemy or nothing, which would you choose? We're the middle children of history, we have no special purpose or place, and unless we get God's attention, we have no hope of damnation or redemption. Which is worse, hell or nothing? Burn the museums, wipe your ass with the Mona Lisa. This way, at least God will know your name.\" - \"Jack\" (Tyler Durden, Fight Club)",
"\"We say atoms are bound by weak attractors. Why not admit the Truth: The universe is held together by Love.\" - Michio Von Kerr (Andromeda)",
"\"If you don't try 100%, why bother trying?\"",
"\"Do or do not, there is no try.\" - Yoda (Star Wars)",
"\"I am a nobody, nobody is perfect, therefore I am perfect.\"",
"\"MYOB - Mind Your Own Business\" - Mr.K",
"\"I am prepared to die, but there is no cause for which I am prepared to kill.\" - Mahatma Gandhi",
"\"Life is a play; you choose whether it is a comedy or a tragedy.\"",
"\"Democracy is two wolves and a sheep deciding what to eat for supper.\"",
"\"Blessed are they who can laugh at themselves, for they shall be forever amused.\"",
"\"If it looks like shit, and it smells like shit, and it tastes like shit; it's probably shit.\"",
"\"In the famous words of Charlie Brown's teacher \"mwa mwa mwa.\"\"",
"\"Don't let kindness get in the way of a dirty deed that must be done.\"",
"\"My brain is stupid, but my heart is smart.\"",
"\"I pray to drunk I'm not God.\"",
"Gabu!",
"Rabu?",
"Nabu.",
"\"The bird of the hermes is my name, eating my wings to keep me tame.\" - The Ripley Scroll",
"\"Why is it that no matter what colour of bubble bath you use the bubbles are always white?\"",
"\"If at first you don't succeed, shouldn't you try doing it like your wife told you to do it?\"",
"\"We begin life suckling on breasts, and with any luck we will end life suckling on breasts, so if your against breasts your against life.\"",
"\"Whatever else I am, whatever else it means, that's the man I want to be. And if I die today, that's the man I'll be.\" - Colonel Tigh (Battlestar Galactica, Reimagined Series)",
"\"Remember remember the 5th of November, the Gunpowder Treason Plot, for I see no reason why Gunpowder Treason Plot should ever be forgot.\"",
"\"Freedom is just another word for nothing left to lose.\" - Janis Joplin",
"\"The reasonable man adapts himself to the world; the unreasonable one persists in trying to adapt the world to himself. Therefore all progress depends on the unreasonable man.\" - George Bernard Shaw"
);
var period = 2520000;           
var d = new Date();
d = d.getTime();                 
d = Math.floor(d/period);        
d = d % quotes.length;
document.write (quotes[d]);